# Simple single-service Docker Compose configuration for the ML pipeline
services:
  ml-pipeline:
    # ports:
    #   - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs

    container_name: mlops-pipeline

    command: python src/ML_pipeline.py